mysite/mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
	url(r'polls/',include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views
app_name='polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^graph_type/$',views.graph_type,name='graph_type'),
    url(r'^piechart_input/$',views.piechart_input,name='piechart_input'),
    url(r'^graph_input/$',views.graph,name='graph_input'),
    url(r'^histogram/$',views.histogram,name='histogram'),
    url(r'^y_as_x/$',views.y_as_x,name='y_as_x'),
    url(r'^z_as_yx/$',views.z_as_yx,name='z_as_yx'),
    url(r'^polar_plot/$',views.polar_plot,name='polar_plot'),
    url(r'^xyz_param/$',views.xyz_param,name='xyz_param'),

]

mysite/graph_app/models.py
from django.db import models

# Create your models here.

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
    	return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
    	return self.choice_text
# Create your models here.

mysite/graph_app/views.py
from django.shortcuts import render

# Create your views here.

mysite/polls/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,Http404,HttpResponseRedirect
from .models import Question,Choice
from django.template import loader
from django.urls import reverse
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt,mpld3
from polls.graph_py.histogram import *
from polls.graph_py.y_as_x import *
from polls.graph_py.z_as_yx import *
from polls.graph_py.polar import *
from polls.graph_py.xyz_param import *
from django.core.files.storage import FileSystemStorage
import json

def graph_type(request):
	return render(request,'polls/graph_type.html')
def xyz_param(request):
	if request.method=="POST":
		x=request.POST['x_function']
		y=request.POST['y_function']
		z=request.POST['z_function']
		ul=float(request.POST['u_lower'])
		uu=float(request.POST['u_upper'])
		vl=float(request.POST['v_lower'])
		vu=float(request.POST['v_upper'])
		xyz_param_graph(x,y,z,ul,uu,vl,vu)
		return render(request,'polls/xyz_param_output.html')
	else:
		return render(request,'polls/xyz_param_input.html')	
def polar_plot(request):
	if request.method=="POST":
		polar_function=request.POST['polar_function']
		polar_lower_limit=request.POST['lower_limit']
		polar_upper_limit=request.POST['upper_limit']
		polar_graph(polar_function,polar_lower_limit,polar_upper_limit)
		return render(request,'polls/polar_output.html')
	else:
		return render(request,'polls/polar_input.html')
def z_as_yx(request):
	if request.method=="POST":
		z_as_yx_input=request.POST['yx_input']
		z_as_yx_plot(z_as_yx_input)
		return render(request,'polls/z_as_yx_output.html')
	else:
		return render(request,'polls/z_as_yx_input.html')

def y_as_x(request):
	if request.method=="POST":
		y_as_x_input=request.POST['y_as_x_input']
		lower_limit=float(request.POST['lower_limit'])
		upper_limit=float(request.POST['upper_limit'])
		# p3=plot(y_as_x_input,show=False)
		y_as_x_graph(y_as_x_input,lower_limit,upper_limit)
		return render(request,'polls/y_as_x_output.html')
	else:
		return render(request,'polls/y_as_x_input.html')
def histogram(request):
	if request.method=="POST":
		hist_file=request.FILES['hist_file']
		hist_file_title=request.POST['hist_file_title']
		hist_file_xlabel=request.POST['hist_file_xlabel']
		hist_file_ylabel=request.POST['hist_file_ylabel']
		data = pd.read_csv(hist_file, sep=',',header=None, index_col =0)
		fig_hist=hist_func(data,hist_file_title,hist_file_xlabel,hist_file_ylabel)
		return render(request,'polls/histogram_output.html',{'fig_hist':fig_hist})
	else:
		return render(request,'polls/histogram_input.html')

def piechart_input(request):
	if request.method=="POST":
		n=request.POST['piechart_input']
		vase_list=range(eval(n))
		return render(request,'polls/after_input.html',{'n':n,'vase_list':vase_list})
	else: 
		return render(request,'polls/give_input.html')
def graph(request):
	if request.method=="POST":
		number_forms=request.POST['number_forms']
		# x='0'
		# for i in range(int(number_forms)):
		# 	x=x+request.POST['after_input'+str(i+1)]
		ar2 = []
		ar3 = []
		for i in range(int(number_forms)):
			ar2.append(request.POST['after_input'+str(i+1)])
			ar3.append(0)
		sizes = ar2
		explode = ar3  # an array corresponding t which elemnts should be exploded. right now no element

		fig1, ax1 = plt.subplots()
		ax1.pie(sizes, explode=explode, autopct='%1.1f%%',shadow=True, startangle=90)
		ax1.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
		plt.plot()
		fig1.savefig('polls/static/polls/pieplot.png')
		#js_data=json.dumps(mpld3.fig_to_dict(fig1))
		fig_html=mpld3.fig_to_html(fig1)
		plt.close()
		#mpld3.show()
		return render(request,'polls/graph.html',{'fig_html':fig_html})
	else:
		return HttpResponse("Not post method")

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    #template=loader.get_template('polls/index.html')
    context={'latest_question_list':latest_question_list,}
    return render(request,'polls/index.html',context)

def detail(request, question_id):
    # try:
    question = get_object_or_404(Question,pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")

    return render(request, 'polls/detail.html', {'question': question})
def results(request, question_id):
    question=get_object_or_404(Question,pk=question_id)
    return render(request,'polls/results.html',{'question':question})
# ...
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/after_input.html
{% load staticfiles %}
<html>
<head>
	<link rel="stylesheet" href="{% static 'css/button.css' %}">
</head>

<body>
<center>
<form action="{% url 'polls:graph_input' %}" method="post">
{% csrf_token %}
Number of fields:<br>
<input type="text" name="number_forms" readonly="readonly" value="{{ n }}"> <br> <br>
<a href="{% url 'polls:piechart_input' %}"> Change number of fields </a> <br> <br>
{% for i in vase_list %}
	<input type="text" name="after_input{{ forloop.counter }}" value="0.0" />  <br>
{% endfor %}<br>
<input type="submit" value="Submit" />
</form>
</center>
</body>
</html>

mysite/polls/templates/polls/detail.html
<!-- <h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/give_input.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/button.css' %}">

<h1> Graph </h1>

<form action="{% url 'polls:piechart_input' %}" method="post">
{% csrf_token %}
Number of fields:
<input type="text" name="piechart_input" />

<input type="submit" value="Submit" />
</form>

mysite/polls/templates/polls/graph.html
{% load staticfiles %}
<!-- 
<img src="{% static 'polls/pieplot.png' %}" alt="mY image"
height='500' />
 -->
 {% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/button.css' %}">
<center>
 {{ fig_html|safe }}
 </center>
<!-- <script type="text/javascript">
	mpld3.draw_figure({{ fig_html }})
	var graph="{{ my_data }}";
	mpld3.draw_figure(graph);

</script> -->
<br>
<a href="{% url 'polls:piechart_input' %}"> Fill input </a><br> <br>
<a href="{% url 'polls:graph_type' %}"> Select graph type </a>

mysite/polls/templates/polls/graph_type.html
{% load staticfiles %}
<html>
<head>
	<link rel="stylesheet" href="{% static 'css/button.css' %}">
</head>

<body>
<center>
<a href="{% url 'polls:piechart_input' %}" > Piechart </a> <br><br>
<a href="{% url 'polls:histogram' %}"> Histogram </a>  <br><br>
 <a href="{% url 'polls:y_as_x' %}"> y as a function of x </a> <br><br>
 <a href="{% url 'polls:z_as_yx' %}"> z as a function of x and y </a> <br><br>
 <a href="{% url 'polls:polar_plot' %}"> Polar Plot </a> <br> <br>
  <a href="{% url 'polls:xyz_param' %}"> x,y,z in parametric form </a> 
  <br>

 <br>
 </center>
</body>
</html>

mysite/polls/templates/polls/histogram_input.html
{% load staticfiles %}
<html>
<head>
	<link rel="stylesheet" href="{% static 'css/button.css' %}">
</head>
<form action="{% url 'polls:histogram' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
<input type="file" name='hist_file'>
 <br><br>
Title of bar graph:<br>
<input type="text" name='hist_file_title'>
 <br>
X-label:<br>
<input type="text" name='hist_file_xlabel'>
 <br>
Y-label:<br>
<input type="text" name='hist_file_ylabel'>
 <br>

<input type="submit" value="Submit" />
</form>

<body>

</body>
</html>

mysite/polls/templates/polls/histogram_output.html
{% load staticfiles %}
<!-- <img src="{% static 'polls/histogram.png' %}" alt="mY image"
height='500' /> -->

<html>
<head>
	<link rel="stylesheet" href="{% static 'css/button.css' %}">
</head>

<body>
<center>
{{ fig_hist|safe }}
</center>
<br>
<a href="{% url 'polls:histogram' %}"> Fill input </a> <br> <br>
<a href="{% url 'polls:graph_type' %}"> Select graph type </a>

</body>
</html>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/polar_output.html
{% load staticfiles %}
<!-- <img src="{% static 'polls/histogram.png' %}" alt="mY image"
height='500' /> -->

<html>
<head>
	<link rel="stylesheet" href="{% static 'css/button.css' %}">
</head>

<body>
<center>
<img src="{% static 'polls/polar_graph.png' %}?cachebuster=polar_as_plot1" alt="mY image"
height='500' />
</center>
<br>
<a href="{% url 'polls:polar_plot' %}"> Plot again </a> <br> <br>
<a href="{% url 'polls:graph_type' %}"> Select graph type </a>

</body>
</html>

mysite/polls/templates/polls/xyz_param_input.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/button.css' %}">

<form action="{% url 'polls:xyz_param' %}" method="post">
{% csrf_token %}
Expression for x in terms of u and v:<br>
<input type="text" name="x_function" /> <br>

Expression for y in terms of u and v:<br>
<input type="text" name="y_function" /> <br>

Expression for z in terms of u and v:<br>
<input type="text" name="z_function" /> <br>

Lower limit of u:<br>
<input type="text" name="u_lower" /> <br>
Upper limit of u:<br>
<input type="text" name="u_upper" /> <br>
Lower limit of v:<br>
<input type="text" name="v_lower" /> <br>
Upper limit of v:<br>
<input type="text" name="v_upper" /> <br><br>

<input type="submit" value="Submit" />
</form>

mysite/polls/templates/polls/xyz_param_output.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/button.css' %}">

<center>
<img src="{% static 'polls/xyz_param.png' %}?cachebuster=xyz_as_param1" alt="mY image"
height='500' />
</center>
<br>
<a href="{% url 'polls:xyz_param' %}"> Plot again </a> <br> <br>
<a href="{% url 'polls:graph_type' %}"> Select graph type </a>

mysite/polls/templates/polls/y_as_x_input.html
{% load staticfiles %}


<html>
<head>
	<link rel="stylesheet" href="{% static 'css/button.css' %}">
</head>
<body>

<form action="{% url 'polls:y_as_x' %}" method="post">
{% csrf_token %}
Funcion y in terms of x:<br>
<input type="text" name='y_as_x_input'> <br>
Set lower limit of x:<br>
<input type="text" name='lower_limit'> <br> 
Set upper limit of x:<br>
<input type="text" name='upper_limit'> <br> 
<input type="submit" value="Submit" class="btn "/>
</form>

</body>
</html>

mysite/polls/templates/polls/y_as_x_output.html
{% load staticfiles %}

<html>
<head>
	<link rel="stylesheet" href="{% static 'css/button.css' %}">
</head>
<body>

<img src="{% static 'polls/y_as_x.png' %}?cachebuster=y_as_x1" alt="mY image"
height='500' />

<!-- {{ fig_y_as_x|safe }} -->
<!--  {{ y_as_x_input }} -->
<br>
<a href="{% url 'polls:y_as_x' %}"> Fill input </a> <br> <br>
<a href="{% url 'polls:graph_type' %}"> Select graph type </a>


</body>
</html>

mysite/polls/templates/polls/z_as_yx_output.html
{% load staticfiles %}

<html>
<head>
<link rel="stylesheet" href="{% static 'css/button.css' %}">	
</head>
<body>
<img src="{% static 'polls/z_as_yx.png' %}?cachebuster=z_as_yx1" alt="mY image"
height='500' />

<!-- {{ fig_y_as_x|safe }} -->
<!--  {{ y_as_x_input }} -->
<br>
<a href="{% url 'polls:z_as_yx' %}"> Fill input </a> <br> <br>
<a href="{% url 'polls:graph_type' %}"> Select graph type </a>


</body>
</html>